### ISSUE TITLE
[local-dev-experience-ui] Users can fund an existing TestNet account in lora

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-lora#180]
## Description

As an AlgoKit user
I want to easily fund an existing TestNet account
So that I have enough ALGO to use my account on the network

## Acceptance Criteria
- Users can login to access the TestNet dispenser API
- Upon entering a valid address and amount, the account is funded with the amount specified using the TestNet dispenser API

## Tasks
- [x] Update the Auth0 email process to use Amazon SES @neilcampbell
- [x] Update any relevant packages in the dispenser API and redeploy the stack @neilcampbell 
- [x] Build the feature @neilcampbell
