### ISSUE TITLE
[local-dev-experience] Users can compose payment transactions

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-lora#216]
## Description

As an AlgoKit user
I want to be able to build payment transactions
So that I can send them to my selected network using my connected wallet

## Technical Details

- Should cater for all variations of payment transactions

## Acceptance Criteria

- The user can build a payment transaction
- The user can send a payment transaction to the selected network using their connected wallet
- The user can reset the entered data

## Tasks
- [ ] Setup the composer page @neilcampbell 
- [ ] Create the payment transaction form @neilcampbell 
- [ ] Create the close payment transaction form
- [ ] Send the transaction
